--this = SceneNode()
LoadingInfo = { 
	"Two towers is better then one",
	"Money stored in the bank is increased when enemys is killed",
	"The only way to win is not to lose",
	"All hints are very helpful",
	"The map is being loaded and compiled into memory",
	"When towers kills the enemy they level up and becomes more powerful",
	"If you fail you can always try again",
	"Upgraded tower do more damge then non uppgraded ones",
	"When enemies dies you earn some gold",
	"By building tower in a maze enemyis need to go furter to get to the end",
	"Mazing the tower is bettern then randomly placing tower around the map",
	"You need to spend money to be victorious",
	"This is a LOADING screen",
	"Human is instructed to wait",
	"Waiting is boring",
	"Loading",
	"Searching for better hints",
	"Round and round it's goes",
	"This game is called Crumbled world",
	"Randome text is displayed down here",
	"Failure is always an option",
	"Victory is optional",
	"A draw is unlikely",
}